version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
     interval: "daily"
     ignore:
      # stay .net 3.1
      - dependency-name: "mcr.microsoft.com/dotnet/runtime"
        versions:
          - "5.x"
          - "6.x"
